# Generated by Django 4.2.6 on 2023-11-02 16:37

import apps.ventas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=155, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('correo_electronico', models.EmailField(max_length=255, verbose_name='Correo Electrónico')),
                ('celular', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de celular')),
                ('nit', models.CharField(blank=True, max_length=55, null=True, verbose_name='NIT')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nit', models.CharField(blank=True, max_length=55, null=True, verbose_name='NIT')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón social')),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Compra', 'Compra')], max_length=125, verbose_name='Tipo')),
                ('detalle', models.TextField(blank=True, max_length=800, null=True, verbose_name='Detalle')),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id_factura', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Compra', 'Compra')], max_length=125, verbose_name='Tipo')),
                ('detalle', models.TextField(blank=True, max_length=800, null=True, verbose_name='Detalle')),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibo',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.CharField(default=apps.ventas.models.conver_encode, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('total', models.FloatField(default=0, verbose_name='Total de la cotizacion')),
                ('impuesto', models.IntegerField(default=0, verbose_name='Impuesto (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.cliente', verbose_name='Cliente')),
                ('insumos', models.ManyToManyField(to='compras.insumo', verbose_name='Insumos')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizacion',
            },
        ),
    ]
