# Generated by Django 4.2.6 on 2023-11-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='ventas.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.FloatField(default=0, editable=False, verbose_name='Total de la cotizacion'),
        ),
    ]
