# Generated by Django 4.2.6 on 2023-11-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_factura_tipo_alter_recibo_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='id_factura',
            new_name='id_recibo',
        ),
    ]
