# Generated by Django 4.2.9 on 2024-02-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_fase_nombre_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='resultadoanalisis',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen en Base64'),
        ),
    ]
