# Generated by Django 4.2.9 on 2024-02-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_fase_nombre_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='resultadoanalisis',
            name='imagen_base64',
        ),
       
        migrations.AddField(
            model_name='resultadoanalisis',
            name='grafica',
            field=models.TextField(blank=True, null=True, verbose_name='Gráfica'),
        ),
    ]
